// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaOIPbOUGeKfgwEJIeNg__RAly2syFfvM',
    appId: '1:69338177227:web:78b403d6e7ef09e05e854e',
    messagingSenderId: '69338177227',
    projectId: 'login-505d6',
    authDomain: 'login-505d6.firebaseapp.com',
    storageBucket: 'login-505d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRT87ktewxtGMIqYnMH3hooFVygVZfdA0',
    appId: '1:69338177227:android:dcb55cb402859beb5e854e',
    messagingSenderId: '69338177227',
    projectId: 'login-505d6',
    storageBucket: 'login-505d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnfDWgeUdOWB3f9caub0mXOISLsWCy2dY',
    appId: '1:69338177227:ios:b75eb817eb1257ef5e854e',
    messagingSenderId: '69338177227',
    projectId: 'login-505d6',
    storageBucket: 'login-505d6.appspot.com',
    iosClientId:
        '69338177227-c5p99ihe41pagupmknfl2crqbtd4k9ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.nomad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnfDWgeUdOWB3f9caub0mXOISLsWCy2dY',
    appId: '1:69338177227:ios:b75eb817eb1257ef5e854e',
    messagingSenderId: '69338177227',
    projectId: 'login-505d6',
    storageBucket: 'login-505d6.appspot.com',
    iosClientId:
        '69338177227-c5p99ihe41pagupmknfl2crqbtd4k9ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.nomad',
  );
}
